spring.application.name=RealEstate_Pro

server.port=9090

spring.data.mongodb.uri=mongodb://localhost:27017/realestate_pro_db

spring.data.mongodb.auto-index-creation=true


jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb25UaGF0SXNMb25nRW5vdWdoMTIzNDU2
jwt.expiration=86400000


# Swagger Configuration



springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html